/**
 * Markdown reporter.
 *
 * Produces a PR-comment-ready summary via pure string templating (no AI/LLM
 * involved). Findings are grouped by severity inside collapsible sections so a
 * large report stays readable in a PR thread.
 */

import { SEVERITIES_DESC } from '../constants.js';
import { VERSION, PRODUCT } from '../version.js';

const SEV_EMOJI = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
};

/** Escape characters that break inline markdown / table cells. */
function esc(text) {
  return String(text ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function code(text) {
  return `\`${String(text ?? '').replace(/`/g, '')}\``;
}

/**
 * @param {object} scan runScan() result.
 * @param {object} [opts] { verbose }
 * @returns {string}
 */
export function render(scan, opts = {}) {
  const verbose = Boolean(opts.verbose);
  const s = scan.summary;
  const stacks = Object.entries(scan.detection.stacks)
    .filter(([, v]) => v)
    .map(([k]) => k);

  const lines = [];
  lines.push(`## 🛡️ ${PRODUCT} Security Scan`);
  lines.push('');
  const verdict = scan.failed
    ? `❌ **Failed** — findings at or above \`${scan.threshold}\` severity`
    : `✅ **Passed** — no findings at or above \`${scan.threshold}\` severity`;
  lines.push(verdict);
  lines.push('');
  lines.push(`**Target:** \`${esc(scan.root)}\`  `);
  lines.push(`**Stack:** ${stacks.length ? stacks.join(', ') : 'unknown'}  `);
  lines.push(`**Scanned:** ${new Date(scan.finishedAt ?? Date.now()).toISOString()}  `);
  lines.push('');

  // Summary table
  lines.push('### Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('| --- | --- |');
  for (const sev of SEVERITIES_DESC) {
    lines.push(`| ${SEV_EMOJI[sev]} ${cap(sev)} | ${s.bySeverity[sev]} |`);
  }
  lines.push(`| **Total** | **${s.total}** |`);
  lines.push('');
  const notes = [];
  if (s.aiCodegen > 0) notes.push(`${s.aiCodegen} match AI-codegen antipatterns`);
  if (scan.suppressedCount > 0) notes.push(`${scan.suppressedCount} suppressed via \`.patronusignore\``);
  if (scan.duplicatesRemoved > 0) notes.push(`${scan.duplicatesRemoved} duplicates merged`);
  if (notes.length) {
    lines.push(`_${notes.join(' · ')}_`);
    lines.push('');
  }

  // Findings
  if (scan.findings.length === 0) {
    lines.push('### Findings');
    lines.push('');
    lines.push('✅ No findings.');
    lines.push('');
  } else {
    lines.push('### Findings');
    lines.push('');
    const groups = groupBySeverity(scan.findings);
    for (const sev of SEVERITIES_DESC) {
      const list = groups[sev];
      if (!list || list.length === 0) continue;
      lines.push(`<details${sev === 'critical' || sev === 'high' ? ' open' : ''}>`);
      lines.push(`<summary>${SEV_EMOJI[sev]} <strong>${cap(sev)}</strong> (${list.length})</summary>`);
      lines.push('');
      for (const f of list) {
        lines.push(renderFindingLine(f, verbose));
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }

  // Analyzer status
  lines.push('### Analyzers');
  lines.push('');
  lines.push('| Analyzer | Status | Findings | Notes |');
  lines.push('| --- | --- | --- | --- |');
  for (const t of scan.toolResults) {
    const count = Array.isArray(t.findings) ? t.findings.length : 0;
    lines.push(`| ${esc(t.id)} | ${t.status} | ${count} | ${esc(t.reason || '')} |`);
  }
  lines.push('');
  lines.push(`<sub>Generated by ${PRODUCT} v${VERSION}. Read-only scan — no code was modified.</sub>`);
  lines.push('');

  return lines.join('\n');
}

function renderFindingLine(f, verbose) {
  const loc = f.file ? code(`${f.file}${f.line != null ? `:${f.line}` : ''}`) : '_(project-wide)_';
  const ai = f.aiCodegenRelevant ? ' `ai-codegen`' : '';
  const agreed =
    Array.isArray(f.agreedTools) && f.agreedTools.length > 1
      ? `, agreed: ${f.agreedTools.join('/')}`
      : '';
  let line = `- **[${esc(f.category)}]** ${loc} — ${esc(f.message)} _(${esc(f.tool)}, ${f.confidence} confidence${agreed})_${ai}`;
  if (verbose) line += ` \`${esc(f.ruleId)}\``;
  if (f.remediation) line += `\n  - _fix:_ ${esc(f.remediation)}`;
  return line;
}

function groupBySeverity(findings) {
  const groups = { critical: [], high: [], medium: [], low: [] };
  for (const f of findings) {
    (groups[f.severity] || (groups[f.severity] = [])).push(f);
  }
  return groups;
}

function cap(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
